package cn.com.lazyhome.qqstatus.bean;

// Generated 2011-3-14 22:03:55 by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * Concern generated by hbm2java
 */
@SuppressWarnings("serial")
public class Concern implements java.io.Serializable {

	private int id;
	private String qqId;
	private Integer delay;
	private String mail;
	private Integer receivedTime;
	private String trace;
	private String traceMail;
	private Date createTime;
	private String createIp;

	public Concern() {
	}

	public Concern(int id, String qqId) {
		this.id = id;
		this.qqId = qqId;
	}

	public Concern(int id, String qqId, Integer delay, String mail,
			Integer receivedTime, Date createTime, String createIp) {
		this.id = id;
		this.qqId = qqId;
		this.delay = delay;
		this.mail = mail;
		this.receivedTime = receivedTime;
		this.createTime = createTime;
		this.createIp = createIp;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getQqId() {
		return this.qqId;
	}

	public void setQqId(String qqId) {
		this.qqId = qqId;
	}

	public Integer getDelay() {
		return this.delay;
	}

	public void setDelay(Integer delay) {
		this.delay = delay;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public Integer getReceivedTime() {
		return this.receivedTime;
	}

	public void setReceivedTime(Integer receivedTime) {
		this.receivedTime = receivedTime;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCreateIp() {
		return this.createIp;
	}

	public void setCreateIp(String createIp) {
		this.createIp = createIp;
	}

	public String getTrace() {
		return trace;
	}

	public void setTrace(String trace) {
		this.trace = trace;
	}

	public String getTraceMail() {
		return traceMail;
	}

	public void setTraceMail(String traceMail) {
		this.traceMail = traceMail;
	}

}
