package cn.com.lazyhome.qqstatus.bean;

// Generated 2011-3-8 21:42:21 by Hibernate Tools 3.3.0.GA

import java.sql.Blob;
import java.util.Date;

/**
 * Log generated by hbm2java
 */
@SuppressWarnings("serial")
public class Log implements java.io.Serializable {

	/**
	 * 主键
	 */
	private int id;
	/**
	 * QQ号
	 */
	private String qqId;
	/**
	 * 状态：1=在线，0=离线
	 */
	private int status;
	/**
	 * 状态文件
	 */
	private Blob file;
	/**
	 * 状态文件大小，通过与预存的文件大小比较，确定是否在线
	 */
	private Integer fileSize;
	/**
	 * 检查时间
	 */
	private Date time;
	
	/**
	 * 关联人
	 */
	private Concern concern;

	public Log() {
	}

	public Log(int id, String qqId, int status, Date time) {
		this.id = id;
		this.qqId = qqId;
		this.status = status;
		this.time = time;
	}

	public Log(int id, String qqId, int status, Blob file, Integer fileSize,
			Date time) {
		this.id = id;
		this.qqId = qqId;
		this.status = status;
		this.file = file;
		this.fileSize = fileSize;
		this.time = time;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getQqId() {
		return this.qqId;
	}

	public void setQqId(String qqId) {
		this.qqId = qqId;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Blob getFile() {
		return this.file;
	}

	public void setFile(Blob file) {
		this.file = file;
	}

	public Integer getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Integer fileSize) {
		this.fileSize = fileSize;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Concern getConcern() {
		return concern;
	}

	public void setConcern(Concern concern) {
		this.concern = concern;
	}

}
