package cn.com.lazyhome.qqstatus.bean;

// Generated 2011-3-8 21:38:07 by Hibernate Tools 3.3.0.GA

/**
 * Qq generated by hbm2java
 */
public class Qq implements java.io.Serializable {

	private int id;
	private String qqId;
	private Integer delay;

	public Qq() {
	}

	public Qq(int id) {
		this.id = id;
	}

	public Qq(int id, String qqId, Integer delay) {
		this.id = id;
		this.qqId = qqId;
		this.delay = delay;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getQqId() {
		return this.qqId;
	}

	public void setQqId(String qqId) {
		this.qqId = qqId;
	}

	public Integer getDelay() {
		return this.delay;
	}

	public void setDelay(Integer delay) {
		this.delay = delay;
	}

}
